- name: Download elasticsearch
  shell: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_repo_version }}.deb && dpkg -i elasticsearch-{{ elasticsearch_repo_version }}.deb

- name: Start ES
  shell:  update-rc.d elasticsearch defaults 95 10 && /etc/init.d/elasticsearch start

- name: Configuring Elasticsearch Defaults
  template: src=default/elasticsearch.j2 dest=/etc/default/elasticsearch owner=root group=root mode=0644
  notify: restart elasticsearch

- name: Configuring Elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify: restart elasticsearch

- name: Install discover-ec2 plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2
#  when: watcher_version_exists.stdout == 'no'
  ignore_errors: yes
  notify: restart elasticsearch

#- name: stop elasticsearch
#  shell: service elasticsearch stop

#- name: Add supervisor config
#  template: src=elasticsearch.conf.j2 dest=/etc/supervisor/conf.d/elasticsearch.conf owner=elasticsearch group=elasticsearch mode=0644
#  notify:
#    - restart supervisor

#- name: update supervisor
#  shell: supervisorctl update
